import { ArchetypeId, Part, PartCategory } from '../../types';

export const STRONG_SUIT_TORSO_PARTS: Part[] = [
  {
    id: 'strong_suit_torso_01_t01',
    name: 'Strong Suit Alpha (Torso 01)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_01_t01.glb',
    priceUSD: 0.8,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_01_t01/100/100',
  },
  {
    id: 'strong_suit_torso_01_t03',
    name: 'Strong Suit Alpha (Torso 03)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_01_t03.glb',
    priceUSD: 0.8,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_01_t03/100/100',
  },
  {
    id: 'strong_suit_torso_01_t05',
    name: 'Strong Suit Alpha (Torso 05)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_01_t05.glb',
    priceUSD: 0.8,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_01_t05/100/100',
  },
  {
    id: 'strong_suit_torso_02_t01',
    name: 'Strong Suit Beta (Torso 01)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_02_t01.glb',
    priceUSD: 0.85,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_02_t01/100/100',
  },
  {
    id: 'strong_suit_torso_02_t03',
    name: 'Strong Suit Beta (Torso 03)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_02_t03.glb',
    priceUSD: 0.85,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_02_t03/100/100',
  },
  {
    id: 'strong_suit_torso_02_t04',
    name: 'Strong Suit Beta (Torso 04)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_02_t04.glb',
    priceUSD: 0.85,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_02_t04/100/100',
  },
  {
    id: 'strong_suit_torso_02_t05',
    name: 'Strong Suit Beta (Torso 05)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_02_t05.glb',
    priceUSD: 0.85,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_02_t05/100/100',
  },
  {
    id: 'strong_suit_torso_03_t01',
    name: 'Strong Suit Gamma (Torso 01)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_03_t01.glb',
    priceUSD: 0.9,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_03_t01/100/100',
  },
  {
    id: 'strong_suit_torso_03_t02',
    name: 'Strong Suit Gamma (Torso 02)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_03_t02.glb',
    priceUSD: 0.9,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_03_t02/100/100',
  },
  {
    id: 'strong_suit_torso_03_t03',
    name: 'Strong Suit Gamma (Torso 03)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_03_t03.glb',
    priceUSD: 0.9,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_03_t03/100/100',
  },
  {
    id: 'strong_suit_torso_03_t04',
    name: 'Strong Suit Gamma (Torso 04)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_03_t04.glb',
    priceUSD: 0.9,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_03_t04/100/100',
  },
  {
    id: 'strong_suit_torso_03_t05',
    name: 'Strong Suit Gamma (Torso 05)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_03_t05.glb',
    priceUSD: 0.9,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_03_t05/100/100',
  },
  {
    id: 'strong_suit_torso_04_t01',
    name: 'Strong Suit Delta (Torso 01)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_04_t01.glb',
    priceUSD: 0.95,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_04_t01/100/100',
  },
  {
    id: 'strong_suit_torso_04_t02',
    name: 'Strong Suit Delta (Torso 02)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_04_t02.glb',
    priceUSD: 0.95,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_04_t02/100/100',
  },
  {
    id: 'strong_suit_torso_04_t03',
    name: 'Strong Suit Delta (Torso 03)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_04_t03.glb',
    priceUSD: 0.95,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_04_t03/100/100',
  },
  {
    id: 'strong_suit_torso_04_t04',
    name: 'Strong Suit Delta (Torso 04)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_04_t04.glb',
    priceUSD: 0.95,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_04_t04/100/100',
  },
  {
    id: 'strong_suit_torso_04_t05',
    name: 'Strong Suit Delta (Torso 05)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_04_t05.glb',
    priceUSD: 0.95,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_04_t05/100/100',
  },
  {
    id: 'strong_suit_torso_01_t02',
    name: 'Strong Suit Alpha (Torso 02)',
    category: PartCategory.SUIT_TORSO,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/suit_torsos/strong_suit_torso_01_t02.glb',
    priceUSD: 0.8,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_suit_torso_01_t02/100/100',
  },
]; 