import { ArchetypeId, Part, PartCategory } from '../../types';

export const STRONG_HANDS_PARTS: Part[] = [
  // fist_01 — t01 (gloved + ungloved)
  {
    id: 'strong_hands_fist_01_t01_l_g',
    name: 'Strong Fist Alpha (Torso 01) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t01_l_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t01_l_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t01_l_ng',
    name: 'Strong Fist Alpha (Torso 01) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t01_l_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t01_l_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t01_r_g',
    name: 'Strong Fist Alpha (Torso 01) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t01_r_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t01_r_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t01_r_ng',
    name: 'Strong Fist Alpha (Torso 01) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t01_r_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t01_r_ng/100/100',
  },
  // fist_01 — t02
  {
    id: 'strong_hands_fist_01_t02_l_g',
    name: 'Strong Fist Alpha (Torso 02) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t02_l_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t02_l_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t02_l_ng',
    name: 'Strong Fist Alpha (Torso 02) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t02_l_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t02_l_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t02_r_g',
    name: 'Strong Fist Alpha (Torso 02) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t02_r_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t02_r_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t02_r_ng',
    name: 'Strong Fist Alpha (Torso 02) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t02_r_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t02_r_ng/100/100',
  },
  // fist_01 — t03
  {
    id: 'strong_hands_fist_01_t03_l_g',
    name: 'Strong Fist Alpha (Torso 03) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t03_l_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t03_l_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t03_l_ng',
    name: 'Strong Fist Alpha (Torso 03) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t03_l_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t03_l_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t03_r_g',
    name: 'Strong Fist Alpha (Torso 03) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t03_r_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t03_r_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t03_r_ng',
    name: 'Strong Fist Alpha (Torso 03) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t03_r_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t03_r_ng/100/100',
  },
  // fist_01 — t04 (only ungloved on disk)
  {
    id: 'strong_hands_fist_01_t04_l_ng',
    name: 'Strong Fist Alpha (Torso 04) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t04_l_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t04_l_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t04_r_ng',
    name: 'Strong Fist Alpha (Torso 04) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t04_r_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t04_r_ng/100/100',
  },
  // fist_01 — t05 (l_g, l_ng, r_ng on disk; r_g missing)
  {
    id: 'strong_hands_fist_01_t05_l_g',
    name: 'Strong Fist Alpha (Torso 05) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t05_l_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t05_l_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t05_l_ng',
    name: 'Strong Fist Alpha (Torso 05) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t05_l_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t05_l_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t05_r_ng',
    name: 'Strong Fist Alpha (Torso 05) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t05_r_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t05_r_ng/100/100',
  },
  // hammer_01 — t01
  {
    id: 'strong_hands_hammer_01_t01_l_g',
    name: 'Strong Hammer Fist 01 (Torso 01) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t01_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t01_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t01_l_ng',
    name: 'Strong Hammer Fist 01 (Torso 01) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t01_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t01_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t01_r_g',
    name: 'Strong Hammer Fist 01 (Torso 01) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t01_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t01_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t01_r_ng',
    name: 'Strong Hammer Fist 01 (Torso 01) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t01_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t01_r_ng/100/100',
  },
  // hammer_01 — t02
  {
    id: 'strong_hands_hammer_01_t02_l_g',
    name: 'Strong Hammer Fist 01 (Torso 02) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t02_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t02_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t02_l_ng',
    name: 'Strong Hammer Fist 01 (Torso 02) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t02_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t02_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t02_r_g',
    name: 'Strong Hammer Fist 01 (Torso 02) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t02_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t02_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t02_r_ng',
    name: 'Strong Hammer Fist 01 (Torso 02) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t02_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t02_r_ng/100/100',
  },
  // hammer_01 — t03
  {
    id: 'strong_hands_hammer_01_t03_l_g',
    name: 'Strong Hammer Fist 01 (Torso 03) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t03_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t03_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t03_l_ng',
    name: 'Strong Hammer Fist 01 (Torso 03) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t03_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t03_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t03_r_g',
    name: 'Strong Hammer Fist 01 (Torso 03) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t03_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t03_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t03_r_ng',
    name: 'Strong Hammer Fist 01 (Torso 03) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t03_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t03_r_ng/100/100',
  },
  // hammer_01 — t04
  {
    id: 'strong_hands_hammer_01_t04_l_g',
    name: 'Strong Hammer Fist 01 (Torso 04) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t04_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t04_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t04_l_ng',
    name: 'Strong Hammer Fist 01 (Torso 04) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t04_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t04_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t04_r_g',
    name: 'Strong Hammer Fist 01 (Torso 04) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t04_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t04_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t04_r_ng',
    name: 'Strong Hammer Fist 01 (Torso 04) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t04_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t04_r_ng/100/100',
  },
  // hammer_01 — t05
  {
    id: 'strong_hands_hammer_01_t05_l_g',
    name: 'Strong Hammer Fist 01 (Torso 05) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t05_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t05_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t05_l_ng',
    name: 'Strong Hammer Fist 01 (Torso 05) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t05_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t05_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t05_r_g',
    name: 'Strong Hammer Fist 01 (Torso 05) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t05_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t05_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_01_t05_r_ng',
    name: 'Strong Hammer Fist 01 (Torso 05) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_01_t05_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_01_t05_r_ng/100/100',
  },
  // hammer_02 — t01 (l_g missing on disk)
  {
    id: 'strong_hands_hammer_02_t01_l_ng',
    name: 'Strong Hammer Fist 02 (Torso 01) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t01_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t01_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t01_r_g',
    name: 'Strong Hammer Fist 02 (Torso 01) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t01_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t01_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t01_r_ng',
    name: 'Strong Hammer Fist 02 (Torso 01) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t01_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t01_r_ng/100/100',
  },
  // hammer_02 — t02
  {
    id: 'strong_hands_hammer_02_t02_l_g',
    name: 'Strong Hammer Fist 02 (Torso 02) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t02_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t02_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t02_l_ng',
    name: 'Strong Hammer Fist 02 (Torso 02) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t02_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t02_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t02_r_g',
    name: 'Strong Hammer Fist 02 (Torso 02) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t02_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t02_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t02_r_ng',
    name: 'Strong Hammer Fist 02 (Torso 02) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t02_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t02_r_ng/100/100',
  },
  // hammer_02 — t03
  {
    id: 'strong_hands_hammer_02_t03_l_g',
    name: 'Strong Hammer Fist 02 (Torso 03) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t03_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t03_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t03_l_ng',
    name: 'Strong Hammer Fist 02 (Torso 03) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t03_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t03_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t03_r_g',
    name: 'Strong Hammer Fist 02 (Torso 03) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t03_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t03_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t03_r_ng',
    name: 'Strong Hammer Fist 02 (Torso 03) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t03_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t03_r_ng/100/100',
  },
  // hammer_02 — t04
  {
    id: 'strong_hands_hammer_02_t04_l_g',
    name: 'Strong Hammer Fist 02 (Torso 04) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t04_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t04_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t04_l_ng',
    name: 'Strong Hammer Fist 02 (Torso 04) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t04_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t04_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t04_r_g',
    name: 'Strong Hammer Fist 02 (Torso 04) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t04_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t04_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t04_r_ng',
    name: 'Strong Hammer Fist 02 (Torso 04) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t04_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t04_r_ng/100/100',
  },
  // hammer_02 — t05
  {
    id: 'strong_hands_hammer_02_t05_l_g',
    name: 'Strong Hammer Fist 02 (Torso 05) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t05_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t05_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t05_l_ng',
    name: 'Strong Hammer Fist 02 (Torso 05) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t05_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t05_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t05_r_g',
    name: 'Strong Hammer Fist 02 (Torso 05) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t05_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t05_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_02_t05_r_ng',
    name: 'Strong Hammer Fist 02 (Torso 05) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_02_t05_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_02_t05_r_ng/100/100',
  },
  // hammer_03 — t01
  {
    id: 'strong_hands_hammer_03_t01_l_g',
    name: 'Strong Hammer Fist 03 (Torso 01) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t01_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t01_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t01_l_ng',
    name: 'Strong Hammer Fist 03 (Torso 01) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t01_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t01_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t01_r_g',
    name: 'Strong Hammer Fist 03 (Torso 01) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t01_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t01_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t01_r_ng',
    name: 'Strong Hammer Fist 03 (Torso 01) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t01_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t01_r_ng/100/100',
  },
  // hammer_03 — t02
  {
    id: 'strong_hands_hammer_03_t02_l_g',
    name: 'Strong Hammer Fist 03 (Torso 02) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t02_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t02_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t02_l_ng',
    name: 'Strong Hammer Fist 03 (Torso 02) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t02_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t02_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t02_r_g',
    name: 'Strong Hammer Fist 03 (Torso 02) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t02_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t02_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t02_r_ng',
    name: 'Strong Hammer Fist 03 (Torso 02) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t02_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t02_r_ng/100/100',
  },
  // hammer_03 — t03
  {
    id: 'strong_hands_hammer_03_t03_l_g',
    name: 'Strong Hammer Fist 03 (Torso 03) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t03_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t03_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t03_l_ng',
    name: 'Strong Hammer Fist 03 (Torso 03) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t03_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t03_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t03_r_g',
    name: 'Strong Hammer Fist 03 (Torso 03) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t03_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t03_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t03_r_ng',
    name: 'Strong Hammer Fist 03 (Torso 03) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t03_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t03_r_ng/100/100',
  },
  // hammer_03 — t04
  {
    id: 'strong_hands_hammer_03_t04_l_g',
    name: 'Strong Hammer Fist 03 (Torso 04) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t04_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t04_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t04_l_ng',
    name: 'Strong Hammer Fist 03 (Torso 04) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t04_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t04_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t04_r_g',
    name: 'Strong Hammer Fist 03 (Torso 04) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t04_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t04_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t04_r_ng',
    name: 'Strong Hammer Fist 03 (Torso 04) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t04_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t04_r_ng/100/100',
  },
  // hammer_03 — t05
  {
    id: 'strong_hands_hammer_03_t05_l_g',
    name: 'Strong Hammer Fist 03 (Torso 05) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t05_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t05_l_g/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t05_l_ng',
    name: 'Strong Hammer Fist 03 (Torso 05) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t05_l_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t05_l_ng/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t05_r_g',
    name: 'Strong Hammer Fist 03 (Torso 05) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t05_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t05_r_g/100/100',
  },
  {
    id: 'strong_hands_hammer_03_t05_r_ng',
    name: 'Strong Hammer Fist 03 (Torso 05) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_hammer_03_t05_r_ng.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_hammer_03_t05_r_ng/100/100',
  },
  // noweapon_01 — t01
  {
    id: 'strong_hands_noweapon_01_t01_l_g',
    name: 'Strong No Weapon 01 (Torso 01) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t01_l_g.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t01_l_g/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t01_l_ng',
    name: 'Strong No Weapon 01 (Torso 01) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t01_l_ng.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t01_l_ng/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t01_r_g',
    name: 'Strong No Weapon 01 (Torso 01) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t01_r_g.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t01_r_g/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t01_r_ng',
    name: 'Strong No Weapon 01 (Torso 01) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t01_r_ng.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t01_r_ng/100/100',
  },
  // noweapon_01 — t02
  {
    id: 'strong_hands_noweapon_01_t02_l_g',
    name: 'Strong No Weapon 01 (Torso 02) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t02_l_g.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t02_l_g/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t02_l_ng',
    name: 'Strong No Weapon 01 (Torso 02) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t02_l_ng.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t02_l_ng/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t02_r_g',
    name: 'Strong No Weapon 01 (Torso 02) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t02_r_g.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t02_r_g/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t02_r_ng',
    name: 'Strong No Weapon 01 (Torso 02) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t02_r_ng.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t02_r_ng/100/100',
  },
  // noweapon_01 — t03
  {
    id: 'strong_hands_noweapon_01_t03_l_g',
    name: 'Strong No Weapon 01 (Torso 03) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t03_l_g.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t03_l_g/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t03_l_ng',
    name: 'Strong No Weapon 01 (Torso 03) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t03_l_ng.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t03_l_ng/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t03_r_g',
    name: 'Strong No Weapon 01 (Torso 03) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t03_r_g.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t03_r_g/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t03_r_ng',
    name: 'Strong No Weapon 01 (Torso 03) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t03_r_ng.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t03_r_ng/100/100',
  },
  // noweapon_01 — t04
  {
    id: 'strong_hands_noweapon_01_t04_l_g',
    name: 'Strong No Weapon 01 (Torso 04) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t04_l_g.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t04_l_g/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t04_l_ng',
    name: 'Strong No Weapon 01 (Torso 04) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t04_l_ng.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t04_l_ng/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t04_r_g',
    name: 'Strong No Weapon 01 (Torso 04) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t04_r_g.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t04_r_g/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t04_r_ng',
    name: 'Strong No Weapon 01 (Torso 04) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t04_r_ng.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t04_r_ng/100/100',
  },
  // noweapon_01 — t05
  {
    id: 'strong_hands_noweapon_01_t05_l_g',
    name: 'Strong No Weapon 01 (Torso 05) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t05_l_g.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t05_l_g/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t05_l_ng',
    name: 'Strong No Weapon 01 (Torso 05) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t05_l_ng.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t05_l_ng/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t05_r_g',
    name: 'Strong No Weapon 01 (Torso 05) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t05_r_g.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t05_r_g/100/100',
  },
  {
    id: 'strong_hands_noweapon_01_t05_r_ng',
    name: 'Strong No Weapon 01 (Torso 05) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_noweapon_01_t05_r_ng.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_noweapon_01_t05_r_ng/100/100',
  },
  // pistol_01 — t01
  {
    id: 'strong_hands_pistol_01_t01_l_g',
    name: 'Strong Pistol 01 (Torso 01) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t01_l_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t01_l_g/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t01_l_ng',
    name: 'Strong Pistol 01 (Torso 01) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t01_l_ng.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t01_l_ng/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t01_r_g',
    name: 'Strong Pistol 01 (Torso 01) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t01_r_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t01_r_g/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t01_r_ng',
    name: 'Strong Pistol 01 (Torso 01) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t01_r_ng.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t01_r_ng/100/100',
  },
  // pistol_01 — t02
  {
    id: 'strong_hands_pistol_01_t02_l_g',
    name: 'Strong Pistol 01 (Torso 02) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t02_l_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t02_l_g/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t02_l_ng',
    name: 'Strong Pistol 01 (Torso 02) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t02_l_ng.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t02_l_ng/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t02_r_g',
    name: 'Strong Pistol 01 (Torso 02) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t02_r_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t02_r_g/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t02_r_ng',
    name: 'Strong Pistol 01 (Torso 02) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t02_r_ng.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t02_r_ng/100/100',
  },
  // pistol_01 — t03
  {
    id: 'strong_hands_pistol_01_t03_l_g',
    name: 'Strong Pistol 01 (Torso 03) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t03_l_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t03_l_g/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t03_l_ng',
    name: 'Strong Pistol 01 (Torso 03) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t03_l_ng.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t03_l_ng/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t03_r_g',
    name: 'Strong Pistol 01 (Torso 03) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t03_r_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t03_r_g/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t03_r_ng',
    name: 'Strong Pistol 01 (Torso 03) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t03_r_ng.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t03_r_ng/100/100',
  },
  // pistol_01 — t04 (l_g missing on disk)
  {
    id: 'strong_hands_pistol_01_t04_l_ng',
    name: 'Strong Pistol 01 (Torso 04) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t04_l_ng.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t04_l_ng/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t04_r_g',
    name: 'Strong Pistol 01 (Torso 04) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t04_r_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t04_r_g/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t04_r_ng',
    name: 'Strong Pistol 01 (Torso 04) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t04_r_ng.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t04_r_ng/100/100',
  },
  // pistol_01 — t05
  {
    id: 'strong_hands_pistol_01_t05_l_g',
    name: 'Strong Pistol 01 (Torso 05) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t05_l_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t05_l_g/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t05_l_ng',
    name: 'Strong Pistol 01 (Torso 05) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t05_l_ng.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t05_l_ng/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t05_r_g',
    name: 'Strong Pistol 01 (Torso 05) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t05_r_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t05_r_g/100/100',
  },
  {
    id: 'strong_hands_pistol_01_t05_r_ng',
    name: 'Strong Pistol 01 (Torso 05) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_pistol_01_t05_r_ng.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_pistol_01_t05_r_ng/100/100',
  },
];
