import { ArchetypeId, Part, PartCategory } from '../../types';

export const STRONG_TORSO_PARTS: Part[] = [
  {
    id: 'strong_torso_01', 
    name: 'Strong Torso Alpha', 
    category: PartCategory.TORSO, 
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/torso/strong_torso_01.glb', 
    priceUSD: 1.50, 
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_torso_01/100/100',
  },
  {
    id: 'strong_torso_02', 
    name: 'Strong Torso Beta', 
    category: PartCategory.TORSO, 
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/torso/strong_torso_02.glb', 
    priceUSD: 1.60, 
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_torso_02/100/100',
  },
  {
    id: 'strong_torso_03', 
    name: 'Strong Torso Gamma', 
    category: PartCategory.TORSO, 
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/torso/strong_torso_03.glb', 
    priceUSD: 1.70, 
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_torso_03/100/100',
  },
  {
    id: 'strong_torso_04', 
    name: 'Strong Torso Delta', 
    category: PartCategory.TORSO, 
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/torso/strong_torso_04.glb', 
    priceUSD: 1.80, 
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_torso_04/100/100',
  },
  {
    id: 'strong_torso_05', 
    name: 'Strong Torso Epsilon', 
    category: PartCategory.TORSO, 
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/torso/strong_torso_05.glb', 
    priceUSD: 1.90, 
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_torso_05/100/100',
  },
]; 