import { ArchetypeId, Part, PartCategory } from '../../types';

export const STRONG_HEAD_PARTS: Part[] = [
  {
    id: 'strong_head_01_t01',
    name: 'Strong Head Alpha (Torso 01)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_01_t01.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_head_01_t01/100/100',
  },
  {
    id: 'strong_head_01_t02',
    name: 'Strong Head Alpha (Torso 02)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_01_t02.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_head_01_t02/100/100',
  },
  {
    id: 'strong_head_01_t03',
    name: 'Strong Head Alpha (Torso 03)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_01_t03.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_head_01_t03/100/100',
  },
  {
    id: 'strong_head_01_t04',
    name: 'Strong Head Alpha (Torso 04)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_01_t04.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_head_01_t04/100/100',
  },
  {
    id: 'strong_head_01_t05',
    name: 'Strong Head Alpha (Torso 05)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_01_t05.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_head_01_t05/100/100',
  },
  {
    id: 'strong_head_02_t01',
    name: 'Strong Head Beta (Torso 01)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_02_t01.glb',
    priceUSD: 0.75,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_head_02_t01/100/100',
  },
  {
    id: 'strong_head_02_t02',
    name: 'Strong Head Beta (Torso 02)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_02_t02.glb',
    priceUSD: 0.75,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_head_02_t02/100/100',
  },
  {
    id: 'strong_head_02_t03',
    name: 'Strong Head Beta (Torso 03)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_02_t03.glb',
    priceUSD: 0.75,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_head_02_t03/100/100',
  },
  {
    id: 'strong_head_02_t04',
    name: 'Strong Head Beta (Torso 04)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_02_t04.glb',
    priceUSD: 0.75,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_head_02_t04/100/100',
  },
  {
    id: 'strong_head_02_t05',
    name: 'Strong Head Beta (Torso 05)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_02_t05.glb',
    priceUSD: 0.75,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_head_02_t05/100/100',
  },
  {
    id: 'strong_head_03_t01',
    name: 'Strong Head Gamma (Torso 01)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_03_t01.glb',
    priceUSD: 0.8,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_head_03_t01/100/100',
  },
  {
    id: 'strong_head_03_t02',
    name: 'Strong Head Gamma (Torso 02)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_03_t02.glb',
    priceUSD: 0.8,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_head_03_t02/100/100',
  },
  {
    id: 'strong_head_03_t03',
    name: 'Strong Head Gamma (Torso 03)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_03_t03.glb',
    priceUSD: 0.8,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_head_03_t03/100/100',
  },
  {
    id: 'strong_head_03_t04',
    name: 'Strong Head Gamma (Torso 04)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_03_t04.glb',
    priceUSD: 0.8,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_head_03_t04/100/100',
  },
  {
    id: 'strong_head_03_t05',
    name: 'Strong Head Gamma (Torso 05)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_03_t05.glb',
    priceUSD: 0.8,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_head_03_t05/100/100',
  },
  {
    id: 'strong_head_04_t01',
    name: 'Strong Head Delta (Torso 01)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_04_t01.glb',
    priceUSD: 0.85,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_head_04_t01/100/100',
  },
  {
    id: 'strong_head_04_t02',
    name: 'Strong Head Delta (Torso 02)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_04_t02.glb',
    priceUSD: 0.85,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_head_04_t02/100/100',
  },
  {
    id: 'strong_head_04_t03',
    name: 'Strong Head Delta (Torso 03)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_04_t03.glb',
    priceUSD: 0.85,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_head_04_t03/100/100',
  },
  {
    id: 'strong_head_04_t04',
    name: 'Strong Head Delta (Torso 04)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_04_t04.glb',
    priceUSD: 0.85,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_head_04_t04/100/100',
  },
  {
    id: 'strong_head_04_t05',
    name: 'Strong Head Delta (Torso 05)',
    category: PartCategory.HEAD,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/head/strong_head_04_t05.glb',
    priceUSD: 0.85,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_head_04_t05/100/100',
  },
]; 