import { ArchetypeId, Part, PartCategory } from '../../types';

export const STRONG_HANDS_PARTS: Part[] = [
  {
    id: 'strong_hands_01_t01_l',
    name: 'Strong Hand Alpha (Torso 01) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_01_t01_l.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_01_t01_l/100/100',
  },
  {
    id: 'strong_hands_01_t01_r',
    name: 'Strong Hand Alpha (Torso 01) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_01_t01_r.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_01_t01_r/100/100',
  },
  {
    id: 'strong_hands_01_t02_l',
    name: 'Strong Hand Alpha (Torso 02) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_01_t02_l.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_01_t02_l/100/100',
  },
  {
    id: 'strong_hands_01_t02_r',
    name: 'Strong Hand Alpha (Torso 02) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_01_t02_r.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_01_t02_r/100/100',
  },
  {
    id: 'strong_hands_01_t03_l',
    name: 'Strong Hand Alpha (Torso 03) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_01_t03_l.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_01_t03_l/100/100',
  },
  {
    id: 'strong_hands_01_t03_r',
    name: 'Strong Hand Alpha (Torso 03) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_01_t03_r.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_01_t03_r/100/100',
  },
  {
    id: 'strong_hands_01_t04_l',
    name: 'Strong Hand Alpha (Torso 04) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_01_t04_l.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_01_t04_l/100/100',
  },
  {
    id: 'strong_hands_01_t04_r',
    name: 'Strong Hand Alpha (Torso 04) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_01_t04_r.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_01_t04_r/100/100',
  },
  {
    id: 'strong_hands_01_t05_l',
    name: 'Strong Hand Alpha (Torso 05) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_01_t05_l.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_01_t05_l/100/100',
  },
  {
    id: 'strong_hands_01_t05_r',
    name: 'Strong Hand Alpha (Torso 05) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_01_t05_r.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_01_t05_r/100/100',
  },
  {
    id: 'strong_hands_fist_01_t01_l_g',
    name: 'Strong Fist Alpha (Torso 01) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t01_l_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t01_l_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t01_l_ng',
    name: 'Strong Fist Alpha (Torso 01) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t01_l_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t01_l_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t01_r_g',
    name: 'Strong Fist Alpha (Torso 01) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t01_r_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t01_r_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t01_r_ng',
    name: 'Strong Fist Alpha (Torso 01) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t01_r_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t01_r_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t02_l_g',
    name: 'Strong Fist Alpha (Torso 02) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t02_l_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t02_l_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t02_l_ng',
    name: 'Strong Fist Alpha (Torso 02) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t02_l_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t02_l_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t02_r_g',
    name: 'Strong Fist Alpha (Torso 02) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t02_r_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t02_r_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t02_r_ng',
    name: 'Strong Fist Alpha (Torso 02) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t02_r_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t02_r_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t03_l_g',
    name: 'Strong Fist Alpha (Torso 03) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t03_l_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t03_l_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t03_l_ng',
    name: 'Strong Fist Alpha (Torso 03) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t03_l_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t03_l_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t03_r_g',
    name: 'Strong Fist Alpha (Torso 03) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t03_r_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t03_r_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t03_r_ng',
    name: 'Strong Fist Alpha (Torso 03) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t03_r_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t03_r_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t04_l',
    name: 'Strong Fist Alpha (Torso 04) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t04_l.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t04_l/100/100',
  },
  {
    id: 'strong_hands_fist_01_t04_l_ng',
    name: 'Strong Fist Alpha (Torso 04) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t04_l_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t04_l_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t04_r',
    name: 'Strong Fist Alpha (Torso 04) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t04_r.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t04_r/100/100',
  },
  {
    id: 'strong_hands_fist_01_t04_r_ng',
    name: 'Strong Fist Alpha (Torso 04) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t04_r_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t04_r_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t05_l',
    name: 'Strong Fist Alpha (Torso 05) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t05_l.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t05_l/100/100',
  },
  {
    id: 'strong_hands_fist_01_t05_l_ng',
    name: 'Strong Fist Alpha (Torso 05) Left (Ungloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t05_l_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t05_l_ng/100/100',
  },
  {
    id: 'strong_hands_fist_01_t05_r',
    name: 'Strong Fist Alpha (Torso 05) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t05_r.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t05_r/100/100',
  },
  {
    id: 'strong_hands_fist_01_t05_r_ng',
    name: 'Strong Fist Alpha (Torso 05) Right (Ungloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t05_r_ng.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t05_r_ng/100/100',
  },
  {
    id: 'strong_hands_bands_01_t01_l',
    name: 'Strong Hands Bands 01 (Torso 01) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t01_l.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t01_l/100/100',
  },
  {
    id: 'strong_hands_bands_01_t01_r',
    name: 'Strong Hands Bands 01 (Torso 01) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t01_r.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t01_r/100/100',
  },
  {
    id: 'strong_hands_bands_01_t02_l',
    name: 'Strong Hands Bands 01 (Torso 02) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t02_l.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t02_l/100/100',
  },
  {
    id: 'strong_hands_bands_01_t02_r',
    name: 'Strong Hands Bands 01 (Torso 02) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t02_r.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t02_r/100/100',
  },
  {
    id: 'strong_hands_bands_01_t03_l',
    name: 'Strong Hands Bands 01 (Torso 03) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t03_l.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t03_l/100/100',
  },
  {
    id: 'strong_hands_bands_01_t03_r',
    name: 'Strong Hands Bands 01 (Torso 03) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t03_r.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t03_r/100/100',
  },
  {
    id: 'strong_hands_bands_01_t04_l',
    name: 'Strong Hands Bands 01 (Torso 04) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t04_l.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t04_l/100/100',
  },
  {
    id: 'strong_hands_bands_01_t04_r',
    name: 'Strong Hands Bands 01 (Torso 04) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t04_r.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t04_r/100/100',
  },
  {
    id: 'strong_hands_bands_01_t05_l',
    name: 'Strong Hands Bands 01 (Torso 05) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t05_l.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t05_l/100/100',
  },
  {
    id: 'strong_hands_bands_01_t05_r',
    name: 'Strong Hands Bands 01 (Torso 05) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t05_r.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t05_r/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t01_l',
    name: 'Strong Gauntlet 01 (Torso 01) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t01_l.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t01_l/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t01_r',
    name: 'Strong Gauntlet 01 (Torso 01) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t01_r.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t01_r/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t02_l',
    name: 'Strong Gauntlet 01 (Torso 02) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t02_l.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t02_l/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t02_r',
    name: 'Strong Gauntlet 01 (Torso 02) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t02_r.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t02_r/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t03_l',
    name: 'Strong Gauntlet 01 (Torso 03) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t03_l.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t03_l/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t03_r',
    name: 'Strong Gauntlet 01 (Torso 03) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t03_r.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t03_r/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t04_l',
    name: 'Strong Gauntlet 01 (Torso 04) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t04_l.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t04_l/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t04_r',
    name: 'Strong Gauntlet 01 (Torso 04) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t04_r.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t04_r/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t05_l',
    name: 'Strong Gauntlet 01 (Torso 05) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t05_l.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t05_l/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t05_r',
    name: 'Strong Gauntlet 01 (Torso 05) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t05_r.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t05_r/100/100',
  },
  {
    id: 'strong_hands_bare_01_t01_l',
    name: 'Strong Bare Hand 01 (Torso 01) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bare_01_t01_l.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bare_01_t01_l/100/100',
  },
  {
    id: 'strong_hands_bare_01_t01_r',
    name: 'Strong Bare Hand 01 (Torso 01) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bare_01_t01_r.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bare_01_t01_r/100/100',
  },
  {
    id: 'strong_hands_bare_01_t02_l',
    name: 'Strong Bare Hand 01 (Torso 02) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bare_01_t02_l.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bare_01_t02_l/100/100',
  },
  {
    id: 'strong_hands_bare_01_t02_r',
    name: 'Strong Bare Hand 01 (Torso 02) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bare_01_t02_r.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bare_01_t02_r/100/100',
  },
  {
    id: 'strong_hands_bare_01_t03_l',
    name: 'Strong Bare Hand 01 (Torso 03) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bare_01_t03_l.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bare_01_t03_l/100/100',
  },
  {
    id: 'strong_hands_bare_01_t03_r',
    name: 'Strong Bare Hand 01 (Torso 03) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bare_01_t03_r.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bare_01_t03_r/100/100',
  },
  {
    id: 'strong_hands_bare_01_t04_l',
    name: 'Strong Bare Hand 01 (Torso 04) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bare_01_t04_l.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bare_01_t04_l/100/100',
  },
  {
    id: 'strong_hands_bare_01_t04_r',
    name: 'Strong Bare Hand 01 (Torso 04) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bare_01_t04_r.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bare_01_t04_r/100/100',
  },
  {
    id: 'strong_hands_bare_01_t05_l',
    name: 'Strong Bare Hand 01 (Torso 05) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bare_01_t05_l.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bare_01_t05_l/100/100',
  },
  {
    id: 'strong_hands_bare_01_t05_r',
    name: 'Strong Bare Hand 01 (Torso 05) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bare_01_t05_r.glb',
    priceUSD: 0.45,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bare_01_t05_r/100/100',
  },
  {
    id: 'strong_hands_fist_01_t01_l',
    name: 'Strong Fist Alpha (Torso 01) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t01_l.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t01_l/100/100',
  },
  {
    id: 'strong_hands_fist_01_t01_r',
    name: 'Strong Fist Alpha (Torso 01) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t01_r.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t01_r/100/100',
  },
  {
    id: 'strong_hands_fist_01_t02_l',
    name: 'Strong Fist Alpha (Torso 02) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t02_l.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t02_l/100/100',
  },
  {
    id: 'strong_hands_fist_01_t02_r',
    name: 'Strong Fist Alpha (Torso 02) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t02_r.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t02_r/100/100',
  },
  {
    id: 'strong_hands_fist_01_t03_l',
    name: 'Strong Fist Alpha (Torso 03) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t03_l.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t03_l/100/100',
  },
  {
    id: 'strong_hands_fist_01_t03_r',
    name: 'Strong Fist Alpha (Torso 03) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t03_r.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t03_r/100/100',
  },
  {
    id: 'strong_hands_fist_01_t04_l_g',
    name: 'Strong Fist Alpha (Torso 04) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t04_l_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t04_l_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t04_r_g',
    name: 'Strong Fist Alpha (Torso 04) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t04_r_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t04_r_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t05_l_g',
    name: 'Strong Fist Alpha (Torso 05) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t05_l_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t05_l_g/100/100',
  },
  {
    id: 'strong_hands_fist_01_t05_r_g',
    name: 'Strong Fist Alpha (Torso 05) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_fist_01_t05_r_g.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_fist_01_t05_r_g/100/100',
  },
  {
    id: 'strong_hands_open_01_t01_l',
    name: 'Strong Open Hand 01 (Torso 01) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_open_01_t01_l.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_open_01_t01_l/100/100',
  },
  {
    id: 'strong_hands_open_01_t01_r',
    name: 'Strong Open Hand 01 (Torso 01) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_open_01_t01_r.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_open_01_t01_r/100/100',
  },
  {
    id: 'strong_hands_open_01_t02_l',
    name: 'Strong Open Hand 01 (Torso 02) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_open_01_t02_l.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_open_01_t02_l/100/100',
  },
  {
    id: 'strong_hands_open_01_t02_r',
    name: 'Strong Open Hand 01 (Torso 02) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_open_01_t02_r.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_open_01_t02_r/100/100',
  },
  {
    id: 'strong_hands_open_01_t03_l',
    name: 'Strong Open Hand 01 (Torso 03) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_open_01_t03_l.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_open_01_t03_l/100/100',
  },
  {
    id: 'strong_hands_open_01_t03_r',
    name: 'Strong Open Hand 01 (Torso 03) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_open_01_t03_r.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_open_01_t03_r/100/100',
  },
  {
    id: 'strong_hands_open_01_t04_l',
    name: 'Strong Open Hand 01 (Torso 04) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_open_01_t04_l.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_open_01_t04_l/100/100',
  },
  {
    id: 'strong_hands_open_01_t04_r',
    name: 'Strong Open Hand 01 (Torso 04) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_open_01_t04_r.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_open_01_t04_r/100/100',
  },
  {
    id: 'strong_hands_open_01_t05_l',
    name: 'Strong Open Hand 01 (Torso 05) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_open_01_t05_l.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_open_01_t05_l/100/100',
  },
  {
    id: 'strong_hands_open_01_t05_r',
    name: 'Strong Open Hand 01 (Torso 05) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_open_01_t05_r.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_open_01_t05_r/100/100',
  },
  {
    id: 'strong_hands_grip_01_t01_l',
    name: 'Strong Grip 01 (Torso 01) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_grip_01_t01_l.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_grip_01_t01_l/100/100',
  },
  {
    id: 'strong_hands_grip_01_t01_r',
    name: 'Strong Grip 01 (Torso 01) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_grip_01_t01_r.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_grip_01_t01_r/100/100',
  },
  {
    id: 'strong_hands_grip_01_t02_l',
    name: 'Strong Grip 01 (Torso 02) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_grip_01_t02_l.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_grip_01_t02_l/100/100',
  },
  {
    id: 'strong_hands_grip_01_t02_r',
    name: 'Strong Grip 01 (Torso 02) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_grip_01_t02_r.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_grip_01_t02_r/100/100',
  },
  {
    id: 'strong_hands_grip_01_t03_l',
    name: 'Strong Grip 01 (Torso 03) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_grip_01_t03_l.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_grip_01_t03_l/100/100',
  },
  {
    id: 'strong_hands_grip_01_t03_r',
    name: 'Strong Grip 01 (Torso 03) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_grip_01_t03_r.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_grip_01_t03_r/100/100',
  },
  {
    id: 'strong_hands_grip_01_t04_l',
    name: 'Strong Grip 01 (Torso 04) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_grip_01_t04_l.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_grip_01_t04_l/100/100',
  },
  {
    id: 'strong_hands_grip_01_t04_r',
    name: 'Strong Grip 01 (Torso 04) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_grip_01_t04_r.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_grip_01_t04_r/100/100',
  },
  {
    id: 'strong_hands_grip_01_t05_l',
    name: 'Strong Grip 01 (Torso 05) Left',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_grip_01_t05_l.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_grip_01_t05_l/100/100',
  },
  {
    id: 'strong_hands_grip_01_t05_r',
    name: 'Strong Grip 01 (Torso 05) Right',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_grip_01_t05_r.glb',
    priceUSD: 0.55,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_grip_01_t05_r/100/100',
  },
  {
    id: 'strong_hands_bands_01_t01_l_g',
    name: 'Strong Hands Bands 01 (Torso 01) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t01_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t01_l_g/100/100',
  },
  {
    id: 'strong_hands_bands_01_t01_r_g',
    name: 'Strong Hands Bands 01 (Torso 01) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t01_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t01_r_g/100/100',
  },
  {
    id: 'strong_hands_bands_01_t02_l_g',
    name: 'Strong Hands Bands 01 (Torso 02) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t02_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t02_l_g/100/100',
  },
  {
    id: 'strong_hands_bands_01_t02_r_g',
    name: 'Strong Hands Bands 01 (Torso 02) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t02_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t02_r_g/100/100',
  },
  {
    id: 'strong_hands_bands_01_t03_l_g',
    name: 'Strong Hands Bands 01 (Torso 03) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t03_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t03_l_g/100/100',
  },
  {
    id: 'strong_hands_bands_01_t03_r_g',
    name: 'Strong Hands Bands 01 (Torso 03) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t03_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t03_r_g/100/100',
  },
  {
    id: 'strong_hands_bands_01_t04_l_g',
    name: 'Strong Hands Bands 01 (Torso 04) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t04_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t04_l_g/100/100',
  },
  {
    id: 'strong_hands_bands_01_t04_r_g',
    name: 'Strong Hands Bands 01 (Torso 04) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t04_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t04_r_g/100/100',
  },
  {
    id: 'strong_hands_bands_01_t05_l_g',
    name: 'Strong Hands Bands 01 (Torso 05) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t05_l_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t05_l_g/100/100',
  },
  {
    id: 'strong_hands_bands_01_t05_r_g',
    name: 'Strong Hands Bands 01 (Torso 05) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_bands_01_t05_r_g.glb',
    priceUSD: 0.65,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_bands_01_t05_r_g/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t01_l_g',
    name: 'Strong Gauntlet 01 (Torso 01) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t01_l_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t01_l_g/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t01_r_g',
    name: 'Strong Gauntlet 01 (Torso 01) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t01_r_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t01_r_g/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t02_l_g',
    name: 'Strong Gauntlet 01 (Torso 02) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t02_l_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t02_l_g/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t02_r_g',
    name: 'Strong Gauntlet 01 (Torso 02) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t02_r_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t02_r_g/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t03_l_g',
    name: 'Strong Gauntlet 01 (Torso 03) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t03_l_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t03_l_g/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t03_r_g',
    name: 'Strong Gauntlet 01 (Torso 03) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t03_r_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t03_r_g/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t04_l_g',
    name: 'Strong Gauntlet 01 (Torso 04) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t04_l_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t04_l_g/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t04_r_g',
    name: 'Strong Gauntlet 01 (Torso 04) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t04_r_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t04_r_g/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t05_l_g',
    name: 'Strong Gauntlet 01 (Torso 05) Left (Gloved)',
    category: PartCategory.HAND_LEFT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t05_l_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t05_l_g/100/100',
  },
  {
    id: 'strong_hands_gauntlet_01_t05_r_g',
    name: 'Strong Gauntlet 01 (Torso 05) Right (Gloved)',
    category: PartCategory.HAND_RIGHT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/hands/strong_hands_gauntlet_01_t05_r_g.glb',
    priceUSD: 0.7,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_hands_gauntlet_01_t05_r_g/100/100',
  },
]; 