import { ArchetypeId, Part, PartCategory } from '../../types';

export const STRONG_BOOTS_PARTS: Part[] = [
  {
    id: 'strong_boots_01_l0',
    name: 'Strong Boots Alpha (Legs 0)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_01_l0.glb',
    priceUSD: 0.4,
    compatible: ['strong_legs_01', 'strong_legs_02', 'strong_legs_03', 'strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_01_l0/100/100',
  },
  {
    id: 'strong_boots_01_l01',
    name: 'Strong Boots Alpha (Legs 01)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_01_l01.glb',
    priceUSD: 0.4,
    compatible: ['strong_legs_01'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_01_l01/100/100',
  },
  {
    id: 'strong_boots_01_l02',
    name: 'Strong Boots Alpha (Legs 02)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_01_l02.glb',
    priceUSD: 0.4,
    compatible: ['strong_legs_02'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_01_l02/100/100',
  },
  {
    id: 'strong_boots_01_l03',
    name: 'Strong Boots Alpha (Legs 03)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_01_l03.glb',
    priceUSD: 0.4,
    compatible: ['strong_legs_03'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_01_l03/100/100',
  },
  {
    id: 'strong_boots_01_l04',
    name: 'Strong Boots Alpha (Legs 04)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_01_l04.glb',
    priceUSD: 0.4,
    compatible: ['strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_01_l04/100/100',
  },
  {
    id: 'strong_boots_02_l0',
    name: 'Strong Boots Beta (Legs 0)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_02_l0.glb',
    priceUSD: 0.45,
    compatible: ['strong_legs_01', 'strong_legs_02', 'strong_legs_03', 'strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_02_l0/100/100',
  },
  {
    id: 'strong_boots_02_l01',
    name: 'Strong Boots Beta (Legs 01)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_02_l01.glb',
    priceUSD: 0.45,
    compatible: ['strong_legs_01'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_02_l01/100/100',
  },
  {
    id: 'strong_boots_02_l02',
    name: 'Strong Boots Beta (Legs 02)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_02_l02.glb',
    priceUSD: 0.45,
    compatible: ['strong_legs_02'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_02_l02/100/100',
  },
  {
    id: 'strong_boots_02_l03',
    name: 'Strong Boots Beta (Legs 03)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_02_l03.glb',
    priceUSD: 0.45,
    compatible: ['strong_legs_03'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_02_l03/100/100',
  },
  {
    id: 'strong_boots_02_l04',
    name: 'Strong Boots Beta (Legs 04)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_02_l04.glb',
    priceUSD: 0.45,
    compatible: ['strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_02_l04/100/100',
  },
  {
    id: 'strong_boots_03_l0',
    name: 'Strong Boots Gamma (Legs 0)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_03_l0.glb',
    priceUSD: 0.5,
    compatible: ['strong_legs_01', 'strong_legs_02', 'strong_legs_03', 'strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_03_l0/100/100',
  },
  {
    id: 'strong_boots_03_l01',
    name: 'Strong Boots Gamma (Legs 01)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_03_l01.glb',
    priceUSD: 0.5,
    compatible: ['strong_legs_01'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_03_l01/100/100',
  },
  {
    id: 'strong_boots_03_l02',
    name: 'Strong Boots Gamma (Legs 02)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_03_l02.glb',
    priceUSD: 0.5,
    compatible: ['strong_legs_02'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_03_l02/100/100',
  },
  {
    id: 'strong_boots_03_l03',
    name: 'Strong Boots Gamma (Legs 03)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_03_l03.glb',
    priceUSD: 0.5,
    compatible: ['strong_legs_03'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_03_l03/100/100',
  },
  {
    id: 'strong_boots_03_l04',
    name: 'Strong Boots Gamma (Legs 04)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_03_l04.glb',
    priceUSD: 0.5,
    compatible: ['strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_03_l04/100/100',
  },
  {
    id: 'strong_boots_04_l0',
    name: 'Strong Boots Delta (Legs 0)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_04_l0.glb',
    priceUSD: 0.55,
    compatible: ['strong_legs_01', 'strong_legs_02', 'strong_legs_03', 'strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_04_l0/100/100',
  },
  {
    id: 'strong_boots_04_l01',
    name: 'Strong Boots Delta (Legs 01)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_04_l01.glb',
    priceUSD: 0.55,
    compatible: ['strong_legs_01'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_04_l01/100/100',
  },
  {
    id: 'strong_boots_04_l02',
    name: 'Strong Boots Delta (Legs 02)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_04_l02.glb',
    priceUSD: 0.55,
    compatible: ['strong_legs_02'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_04_l02/100/100',
  },
  {
    id: 'strong_boots_04_l03',
    name: 'Strong Boots Delta (Legs 03)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_04_l03.glb',
    priceUSD: 0.55,
    compatible: ['strong_legs_03'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_04_l03/100/100',
  },
  {
    id: 'strong_boots_04_l04',
    name: 'Strong Boots Delta (Legs 04)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_04_l04.glb',
    priceUSD: 0.55,
    compatible: ['strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_04_l04/100/100',
  },
  {
    id: 'strong_boots_05_l0',
    name: 'Strong Boots Epsilon (Legs 0)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_05_l0.glb',
    priceUSD: 0.6,
    compatible: ['strong_legs_01', 'strong_legs_02', 'strong_legs_03', 'strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_05_l0/100/100',
  },
  {
    id: 'strong_boots_05_l01',
    name: 'Strong Boots Epsilon (Legs 01)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_05_l01.glb',
    priceUSD: 0.6,
    compatible: ['strong_legs_01'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_05_l01/100/100',
  },
  {
    id: 'strong_boots_05_l02',
    name: 'Strong Boots Epsilon (Legs 02)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_05_l02.glb',
    priceUSD: 0.6,
    compatible: ['strong_legs_02'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_05_l02/100/100',
  },
  {
    id: 'strong_boots_05_l03',
    name: 'Strong Boots Epsilon (Legs 03)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_05_l03.glb',
    priceUSD: 0.6,
    compatible: ['strong_legs_03'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_05_l03/100/100',
  },
  {
    id: 'strong_boots_05_l04',
    name: 'Strong Boots Epsilon (Legs 04)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_05_l04.glb',
    priceUSD: 0.6,
    compatible: ['strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_05_l04/100/100',
  },
  {
    id: 'strong_boots_06_l0',
    name: 'Strong Boots Zeta (Legs 0)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_06_l0.glb',
    priceUSD: 0.65,
    compatible: ['strong_legs_01', 'strong_legs_02', 'strong_legs_03', 'strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_06_l0/100/100',
  },
  {
    id: 'strong_boots_06_l01',
    name: 'Strong Boots Zeta (Legs 01)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_06_l01.glb',
    priceUSD: 0.65,
    compatible: ['strong_legs_01'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_06_l01/100/100',
  },
  {
    id: 'strong_boots_06_l02',
    name: 'Strong Boots Zeta (Legs 02)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_06_l02.glb',
    priceUSD: 0.65,
    compatible: ['strong_legs_02'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_06_l02/100/100',
  },
  {
    id: 'strong_boots_06_l03',
    name: 'Strong Boots Zeta (Legs 03)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_06_l03.glb',
    priceUSD: 0.65,
    compatible: ['strong_legs_03'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_06_l03/100/100',
  },
  {
    id: 'strong_boots_06_l04',
    name: 'Strong Boots Zeta (Legs 04)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_06_l04.glb',
    priceUSD: 0.65,
    compatible: ['strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_06_l04/100/100',
  },
  {
    id: 'strong_boots_07_l0',
    name: 'Strong Boots Eta (Legs 0)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_07_l0.glb',
    priceUSD: 0.7,
    compatible: ['strong_legs_01', 'strong_legs_02', 'strong_legs_03', 'strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_07_l0/100/100',
  },
  {
    id: 'strong_boots_07_l01',
    name: 'Strong Boots Eta (Legs 01)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_07_l01.glb',
    priceUSD: 0.7,
    compatible: ['strong_legs_01'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_07_l01/100/100',
  },
  {
    id: 'strong_boots_07_l02',
    name: 'Strong Boots Eta (Legs 02)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_07_l02.glb',
    priceUSD: 0.7,
    compatible: ['strong_legs_02'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_07_l02/100/100',
  },
  {
    id: 'strong_boots_07_l03',
    name: 'Strong Boots Eta (Legs 03)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_07_l03.glb',
    priceUSD: 0.7,
    compatible: ['strong_legs_03'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_07_l03/100/100',
  },
  {
    id: 'strong_boots_07_l04',
    name: 'Strong Boots Eta (Legs 04)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_07_l04.glb',
    priceUSD: 0.7,
    compatible: ['strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_07_l04/100/100',
  },
  {
    id: 'strong_boots_08_l0',
    name: 'Strong Boots Theta (Legs 0)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_08_l0.glb',
    priceUSD: 0.75,
    compatible: ['strong_legs_01', 'strong_legs_02', 'strong_legs_03', 'strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_08_l0/100/100',
  },
  {
    id: 'strong_boots_08_l01',
    name: 'Strong Boots Theta (Legs 01)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_08_l01.glb',
    priceUSD: 0.75,
    compatible: ['strong_legs_01'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_08_l01/100/100',
  },
  {
    id: 'strong_boots_08_l02',
    name: 'Strong Boots Theta (Legs 02)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_08_l02.glb',
    priceUSD: 0.75,
    compatible: ['strong_legs_02'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_08_l02/100/100',
  },
  {
    id: 'strong_boots_08_l03',
    name: 'Strong Boots Theta (Legs 03)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_08_l03.glb',
    priceUSD: 0.75,
    compatible: ['strong_legs_03'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_08_l03/100/100',
  },
  {
    id: 'strong_boots_08_l04',
    name: 'Strong Boots Theta (Legs 04)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_08_l04.glb',
    priceUSD: 0.75,
    compatible: ['strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_08_l04/100/100',
  },
  {
    id: 'strong_boots_09_l0',
    name: 'Strong Boots Iota (Legs 0)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_09_l0.glb',
    priceUSD: 0.8,
    compatible: ['strong_legs_01', 'strong_legs_02', 'strong_legs_03', 'strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_09_l0/100/100',
  },
  {
    id: 'strong_boots_09_l01',
    name: 'Strong Boots Iota (Legs 01)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_09_l01.glb',
    priceUSD: 0.8,
    compatible: ['strong_legs_01'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_09_l01/100/100',
  },
  {
    id: 'strong_boots_09_l02',
    name: 'Strong Boots Iota (Legs 02)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_09_l02.glb',
    priceUSD: 0.8,
    compatible: ['strong_legs_02'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_09_l02/100/100',
  },
  {
    id: 'strong_boots_09_l03',
    name: 'Strong Boots Iota (Legs 03)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_09_l03.glb',
    priceUSD: 0.8,
    compatible: ['strong_legs_03'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_09_l03/100/100',
  },
  {
    id: 'strong_boots_09_l04',
    name: 'Strong Boots Iota (Legs 04)',
    category: PartCategory.BOOTS,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/boots/strong_boots_09_l04.glb',
    priceUSD: 0.8,
    compatible: ['strong_legs_04'],
    thumbnail: 'https://picsum.photos/seed/strong_boots_09_l04/100/100',
  },
]; 