import { ArchetypeId, Part, PartCategory } from '../../types';

export const STRONG_BUCKLE_PARTS: Part[] = [
  {
    id: 'strong_buckle_01',
    name: 'Classic Buckle',
    category: PartCategory.BUCKLE,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/buckle/strong_buckle_01.glb',
    priceUSD: 0,
    freeForAll: true,
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_buckle_01/100/100',
  },
  {
    id: 'strong_buckle_02',
    name: 'Heroic Buckle',
    category: PartCategory.BUCKLE,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/buckle/strong_buckle_02.glb',
    priceUSD: 0.12,
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_buckle_02/100/100',
  },
  {
    id: 'strong_buckle_03',
    name: 'Tactical Buckle',
    category: PartCategory.BUCKLE,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/buckle/strong_buckle_03.glb',
    priceUSD: 0.15,
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_buckle_03/100/100',
  },
  {
    id: 'strong_buckle_04',
    name: 'Elite Buckle',
    category: PartCategory.BUCKLE,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/buckle/strong_buckle_04.glb',
    priceUSD: 0.18,
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_buckle_04/100/100',
  },
  {
    id: 'strong_buckle_05',
    name: 'Combat Buckle',
    category: PartCategory.BUCKLE,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/buckle/strong_buckle_05.glb',
    priceUSD: 0.20,
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_buckle_05/100/100',
  },
  {
    id: 'strong_buckle_06',
    name: 'Premium Buckle',
    category: PartCategory.BUCKLE,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/buckle/strong_buckle_06.glb',
    priceUSD: 0.25,
    compatible: [],
    thumbnail: 'https://picsum.photos/seed/strong_buckle_06/100/100',
  },
]; 