import { ArchetypeId, Part, PartCategory } from '../../types';

export const STRONG_SYMBOL_PARTS: Part[] = [
  {
    id: 'strong_symbol_01_ns',
    name: 'Strong Symbol Alpha (No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_ns.glb',
    priceUSD: 0,
    freeForAll: true,
    compatible: ['strong_torso_01', 'strong_torso_02', 'strong_torso_03', 'strong_torso_04', 'strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_ns/100/100',
  },
  {
    id: 'strong_symbol_01_t01_ns',
    name: 'Strong Symbol Alpha (Torso 01 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_t01_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_t01_ns/100/100',
  },
  {
    id: 'strong_symbol_01_t01',
    name: 'Strong Symbol Alpha (Torso 01)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_t01.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_t01/100/100',
  },
  {
    id: 'strong_symbol_01_t02_ns',
    name: 'Strong Symbol Alpha (Torso 02 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_t02_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_t02_ns/100/100',
  },
  {
    id: 'strong_symbol_01_t02',
    name: 'Strong Symbol Alpha (Torso 02)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_t02.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_t02/100/100',
  },
  {
    id: 'strong_symbol_01_t03_ns',
    name: 'Strong Symbol Alpha (Torso 03 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_t03_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_t03_ns/100/100',
  },
  {
    id: 'strong_symbol_01_t03',
    name: 'Strong Symbol Alpha (Torso 03)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_t03.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_t03/100/100',
  },
  {
    id: 'strong_symbol_01_t04_ns',
    name: 'Strong Symbol Alpha (Torso 04 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_t04_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_t04_ns/100/100',
  },
  {
    id: 'strong_symbol_01_t04',
    name: 'Strong Symbol Alpha (Torso 04)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_t04.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_t04/100/100',
  },
  {
    id: 'strong_symbol_01_t05_ns',
    name: 'Strong Symbol Alpha (Torso 05 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_t05_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_t05_ns/100/100',
  },
  {
    id: 'strong_symbol_01_t05',
    name: 'Strong Symbol Alpha (Torso 05)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_01_t05.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_01_t05/100/100',
  },
  {
    id: 'strong_symbol_02_ns',
    name: 'Strong Symbol Beta (No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_01', 'strong_torso_02', 'strong_torso_03', 'strong_torso_04', 'strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_ns/100/100',
  },
  {
    id: 'strong_symbol_02_t01_ns',
    name: 'Strong Symbol Beta (Torso 01 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_t01_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_t01_ns/100/100',
  },
  {
    id: 'strong_symbol_02_t01',
    name: 'Strong Symbol Beta (Torso 01)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_t01.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_t01/100/100',
  },
  {
    id: 'strong_symbol_02_t02_ns',
    name: 'Strong Symbol Beta (Torso 02 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_t02_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_t02_ns/100/100',
  },
  {
    id: 'strong_symbol_02_t02',
    name: 'Strong Symbol Beta (Torso 02)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_t02.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_t02/100/100',
  },
  {
    id: 'strong_symbol_02_t03_ns',
    name: 'Strong Symbol Beta (Torso 03 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_t03_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_t03_ns/100/100',
  },
  {
    id: 'strong_symbol_02_t03',
    name: 'Strong Symbol Beta (Torso 03)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_t03.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_t03/100/100',
  },
  {
    id: 'strong_symbol_02_t04_ns',
    name: 'Strong Symbol Beta (Torso 04 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_t04_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_t04_ns/100/100',
  },
  {
    id: 'strong_symbol_02_t04',
    name: 'Strong Symbol Beta (Torso 04)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_t04.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_t04/100/100',
  },
  {
    id: 'strong_symbol_02_t05_ns',
    name: 'Strong Symbol Beta (Torso 05 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_t05_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_t05_ns/100/100',
  },
  {
    id: 'strong_symbol_02_t05',
    name: 'Strong Symbol Beta (Torso 05)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_02_t05.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_02_t05/100/100',
  },
  {
    id: 'strong_symbol_03_ns',
    name: 'Strong Symbol Gamma (No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_01', 'strong_torso_02', 'strong_torso_03', 'strong_torso_04', 'strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_ns/100/100',
  },
  {
    id: 'strong_symbol_03_t01_ns',
    name: 'Strong Symbol Gamma (Torso 01 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_t01_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_t01_ns/100/100',
  },
  {
    id: 'strong_symbol_03_t01',
    name: 'Strong Symbol Gamma (Torso 01)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_t01.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_t01/100/100',
  },
  {
    id: 'strong_symbol_03_t02_ns',
    name: 'Strong Symbol Gamma (Torso 02 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_t02_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_t02_ns/100/100',
  },
  {
    id: 'strong_symbol_03_t02',
    name: 'Strong Symbol Gamma (Torso 02)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_t02.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_t02/100/100',
  },
  {
    id: 'strong_symbol_03_t03_ns',
    name: 'Strong Symbol Gamma (Torso 03 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_t03_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_t03_ns/100/100',
  },
  {
    id: 'strong_symbol_03_t03',
    name: 'Strong Symbol Gamma (Torso 03)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_t03.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_t03/100/100',
  },
  {
    id: 'strong_symbol_03_t04_ns',
    name: 'Strong Symbol Gamma (Torso 04 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_t04_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_t04_ns/100/100',
  },
  {
    id: 'strong_symbol_03_t04',
    name: 'Strong Symbol Gamma (Torso 04)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_t04.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_t04/100/100',
  },
  {
    id: 'strong_symbol_03_t05_ns',
    name: 'Strong Symbol Gamma (Torso 05 No Symbol)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_t05_ns.glb',
    priceUSD: 0.1,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_t05_ns/100/100',
  },
  {
    id: 'strong_symbol_03_t05',
    name: 'Strong Symbol Gamma (Torso 05)',
    category: PartCategory.SYMBOL,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/symbol/strong_symbol_03_t05.glb',
    priceUSD: 0.2,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_symbol_03_t05/100/100',
  },
]; 