import { ArchetypeId, Part, PartCategory } from '../../types';

export const STRONG_CHEST_BELT_PARTS: Part[] = [
  {
    id: 'strong_beltchest_01_np',
    name: 'Strong Chest Belt 01 (No Pouch)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_np.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01', 'strong_torso_02', 'strong_torso_03', 'strong_torso_04', 'strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_np/100/100',
  },
  {
    id: 'strong_beltchest_01_t01_np',
    name: 'Strong Chest Belt 01 (Torso 01 No Pouch)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_t01_np.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_t01_np/100/100',
  },
  {
    id: 'strong_beltchest_01_t01',
    name: 'Strong Chest Belt 01 (Torso 01)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_t01.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_01'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_t01/100/100',
  },
  {
    id: 'strong_beltchest_01_t02_np',
    name: 'Strong Chest Belt 01 (Torso 02 No Pouch)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_t02_np.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_t02_np/100/100',
  },
  {
    id: 'strong_beltchest_01_t02',
    name: 'Strong Chest Belt 01 (Torso 02)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_t02.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_02'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_t02/100/100',
  },
  {
    id: 'strong_beltchest_01_t03_np',
    name: 'Strong Chest Belt 01 (Torso 03 No Pouch)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_t03_np.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_t03_np/100/100',
  },
  {
    id: 'strong_beltchest_01_t03',
    name: 'Strong Chest Belt 01 (Torso 03)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_t03.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_03'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_t03/100/100',
  },
  {
    id: 'strong_beltchest_01_t04_np',
    name: 'Strong Chest Belt 01 (Torso 04 No Pouch)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_t04_np.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_t04_np/100/100',
  },
  {
    id: 'strong_beltchest_01_t04',
    name: 'Strong Chest Belt 01 (Torso 04)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_t04.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_04'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_t04/100/100',
  },
  {
    id: 'strong_beltchest_01_t05_np',
    name: 'Strong Chest Belt 01 (Torso 05 No Pouch)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_t05_np.glb',
    priceUSD: 0.5,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_t05_np/100/100',
  },
  {
    id: 'strong_beltchest_01_t05',
    name: 'Strong Chest Belt 01 (Torso 05)',
    category: PartCategory.CHEST_BELT,
    archetype: ArchetypeId.STRONG,
    gltfPath: 'assets/strong/chest_belt/strong_beltchest_01_t05.glb',
    priceUSD: 0.6,
    compatible: ['strong_torso_05'],
    thumbnail: 'https://picsum.photos/seed/strong_beltchest_01_t05/100/100',
  },
]; 